### PR TITLE
Adds https://YeatmanLab.github.io/DevCogNeuro/

### PR DESCRIPTION
**Pull request by jyeatman**
Auto-created by afqbrowser-publish

### CODE REVIEW

**Comment by arokem** [comment]
🙌

**Comment by arokem** [comment]
Looks like I broke the build when merging this. 

@akeshavan : do you understand the CI errors?

**Comment by akeshavan** [comment]
Is there a CI error? I see it on the Vault. Actually I see two entries! (need to look into why that happened)

**Comment by akeshavan** [comment]
oh, JK https://github.com/afqvault/afqvault/blob/master/upload.py#L134 if there is ever an update on the repo, the vault grabs it. So that's fine

**Comment by arokem** [comment]
The first run failed for me, but then the cron job ran through.

**Pull request merged**
