### PR TITLE
Adds https://yeatmanlab.github.io/anothersite/

### PR DESCRIPTION
**Pull request by arokem**
Auto-created by afqbrowser-publish

### CODE REVIEW

**Comment by arokem** [comment]
Don't merge this one, please!

**Comment by arokem** [comment]
I seem to have some conflicts on my fork... But that's probably fine...

**Comment by akeshavan** [comment]
ok I'll close this!

**Comment by arokem** [comment]
Thanks!

**Comment by arokem** [comment]
This was an experiment for https://github.com/yeatmanlab/AFQ-Browser/pull/249

**Pull request closed without merging**
